language: node_js
node_js:
- '0.10'
install:
- npm install
- npm install -g gulp
before_deploy:
- gulp build
deploy:
  provider: s3
  access_key_id: AKIAII7TI4JOMGRAWTNA
  bucket: cc.silktide.com
  local-dir: build
  skip_cleanup: true
  on:
    repo: silktide/cookieconsent2
    all_branches: true
  secret_access_key:
    secure: CPm+hc3WNR5ebywuqtAeyO4gHNllWqpIyiMRWzqJfcHWluF2nuI3wib9nvIHkxvhWqezOyyfF5rFb9NerDKzWqARL+a7+rMSchdT94l5x4lZ0oyf1DFh16qwKE706jdj5A4jBUMdE/tqW59wcNxKD+eAmVo/e/pySZKz/yaxSgM=
